module.exports=[
    {
        week:1,
        exersicequatos:[
            {
                days:5,
                totalquota:50,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                    {name:"workout",pert:14}
                ]
            },
            {
                days:4,
                totalquota:40,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                   
                ]
            },
            {
                days:3,
                totalquota:30,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17}
                ]
            },
            {
                days:2,
                totalquota:20,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20}
                ]
            }
        ]    
    },
    {
        week:2,
        exersicequatos:[
            {
                days:5,
                totalquota:50,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                    {name:"workout",pert:14}
                ]
            },
            {
                days:4,
                totalquota:40,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                   
                ]
            },
            {
                days:3,
                totalquota:50,
                workouts:[
                    {name:"workout",pert:87},
                    {name:"workout",pert:8},
                    {name:"workout",pert:6}
                ]
            },
            {
                days:2,
                totalquota:20,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20}
                ]
            }
        ]    
    }, {
        week:3,
        exersicequatos:[
            {
                days:5,
                totalquota:50,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                    {name:"workout",pert:14}
                ]
            },
            {
                days:4,
                totalquota:40,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                   
                ]
            },
            {
                days:3,
                totalquota:70,
                workouts:[
                    {name:"workout",pert:15},
                    {name:"workout",pert:15},
                    {name:"workout",pert:45}
                ]
            },
            {
                days:2,
                totalquota:20,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20}
                ]
            }
        ]    
    }, {
        week:4,
        exersicequatos:[
            {
                days:5,
                totalquota:50,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                    {name:"workout",pert:14}
                ]
            },
            {
                days:4,
                totalquota:40,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:17},
                    {name:"workout",pert:13},
                   
                ]
            },
            {
                days:3,
                totalquota:20,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20},
                    {name:"workout",pert:19}
                ]
            },
            {
                days:2,
                totalquota:20,
                workouts:[
                    {name:"workout",pert:37},
                    {name:"workout",pert:20}
                ]
            }
        ]    
    },
]

