module.exports=[
    {
        week:1,
        workouts:{
            workout1:37,
            workout2:20,
            workout3:17,
            workout4:13,
            workout5:12
        }
    },
    {
        week:2,
        workouts:{
            workout1:35,
            workout2:20,
            workout3:17,
            workout4:13,
            workout5:14
        }
    },
    {
        week:3,
        workouts:{
            workout1:35,
            workout2:8,
            workout3:17,
            workout4:13,
            workout5:24
        }
    },
    {
        week:1,
        workouts:{
            workout1:37,
            workout2:20,
            workout3:23,
            workout4:7,
            workout5:12
        }
    }
    
]